package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ingreso generated by hbm2java
 */
public class Ingreso  implements java.io.Serializable {


     private IngresoId id;
     private OperarioUser operarioUser;
     private UsuarioVehiculo usuarioVehiculo;
     private Date fechaSalida;
     private String estado;

    public Ingreso() {
    }

	
    public Ingreso(IngresoId id, OperarioUser operarioUser, UsuarioVehiculo usuarioVehiculo) {
        this.id = id;
        this.operarioUser = operarioUser;
        this.usuarioVehiculo = usuarioVehiculo;
    }
    public Ingreso(IngresoId id, OperarioUser operarioUser, UsuarioVehiculo usuarioVehiculo, Date fechaSalida, String estado) {
       this.id = id;
       this.operarioUser = operarioUser;
       this.usuarioVehiculo = usuarioVehiculo;
       this.fechaSalida = fechaSalida;
       this.estado = estado;
    }
   
    public IngresoId getId() {
        return this.id;
    }
    
    public void setId(IngresoId id) {
        this.id = id;
    }
    public OperarioUser getOperarioUser() {
        return this.operarioUser;
    }
    
    public void setOperarioUser(OperarioUser operarioUser) {
        this.operarioUser = operarioUser;
    }
    public UsuarioVehiculo getUsuarioVehiculo() {
        return this.usuarioVehiculo;
    }
    
    public void setUsuarioVehiculo(UsuarioVehiculo usuarioVehiculo) {
        this.usuarioVehiculo = usuarioVehiculo;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


