package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OperarioUser generated by hbm2java
 */
public class OperarioUser  implements java.io.Serializable {


     private String nombreUsuarioOperario;
     private TipoOperarioUser tipoOperarioUser;
     private String password;
     private Set ingresos = new HashSet(0);
     private Set operarios = new HashSet(0);

    public OperarioUser() {
    }

	
    public OperarioUser(String nombreUsuarioOperario, TipoOperarioUser tipoOperarioUser, String password) {
        this.nombreUsuarioOperario = nombreUsuarioOperario;
        this.tipoOperarioUser = tipoOperarioUser;
        this.password = password;
    }
    public OperarioUser(String nombreUsuarioOperario, TipoOperarioUser tipoOperarioUser, String password, Set ingresos, Set operarios) {
       this.nombreUsuarioOperario = nombreUsuarioOperario;
       this.tipoOperarioUser = tipoOperarioUser;
       this.password = password;
       this.ingresos = ingresos;
       this.operarios = operarios;
    }
   
    public String getNombreUsuarioOperario() {
        return this.nombreUsuarioOperario;
    }
    
    public void setNombreUsuarioOperario(String nombreUsuarioOperario) {
        this.nombreUsuarioOperario = nombreUsuarioOperario;
    }
    public TipoOperarioUser getTipoOperarioUser() {
        return this.tipoOperarioUser;
    }
    
    public void setTipoOperarioUser(TipoOperarioUser tipoOperarioUser) {
        this.tipoOperarioUser = tipoOperarioUser;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set ingresos) {
        this.ingresos = ingresos;
    }
    public Set getOperarios() {
        return this.operarios;
    }
    
    public void setOperarios(Set operarios) {
        this.operarios = operarios;
    }




}


