package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1



/**
 * Operario generated by hbm2java
 */
public class Operario  implements java.io.Serializable {


     private String identificacion;
     private OperarioUser operarioUser;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;

    public Operario() {
    }

	
    public Operario(String identificacion, OperarioUser operarioUser, String nombre, String apellido, String telefono) {
        this.identificacion = identificacion;
        this.operarioUser = operarioUser;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
    }
    public Operario(String identificacion, OperarioUser operarioUser, String nombre, String apellido, String direccion, String telefono) {
       this.identificacion = identificacion;
       this.operarioUser = operarioUser;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public OperarioUser getOperarioUser() {
        return this.operarioUser;
    }
    
    public void setOperarioUser(OperarioUser operarioUser) {
        this.operarioUser = operarioUser;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


