package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoIdentificacion generated by hbm2java
 */
public class TipoIdentificacion  implements java.io.Serializable {


     private int idTipoIdentificacion;
     private String tipoIdentificacionDescripcion;
     private Set usuarios = new HashSet(0);

    public TipoIdentificacion() {
    }

	
    public TipoIdentificacion(int idTipoIdentificacion, String tipoIdentificacionDescripcion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
        this.tipoIdentificacionDescripcion = tipoIdentificacionDescripcion;
    }
    public TipoIdentificacion(int idTipoIdentificacion, String tipoIdentificacionDescripcion, Set usuarios) {
       this.idTipoIdentificacion = idTipoIdentificacion;
       this.tipoIdentificacionDescripcion = tipoIdentificacionDescripcion;
       this.usuarios = usuarios;
    }
   
    public int getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(int idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public String getTipoIdentificacionDescripcion() {
        return this.tipoIdentificacionDescripcion;
    }
    
    public void setTipoIdentificacionDescripcion(String tipoIdentificacionDescripcion) {
        this.tipoIdentificacionDescripcion = tipoIdentificacionDescripcion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


