package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1

/**
 * TipoIdentificacion generated by hbm2java
 */
public class TipoIdentificacion  implements java.io.Serializable {


     private int idTipoIdentificacion;
     private String tipoIdentificacionDescripcion;

    public TipoIdentificacion() {
    }

	
    public TipoIdentificacion(int idTipoIdentificacion, String tipoIdentificacionDescripcion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
        this.tipoIdentificacionDescripcion = tipoIdentificacionDescripcion;
    }
   
    public int getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(int idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public String getTipoIdentificacionDescripcion() {
        return this.tipoIdentificacionDescripcion;
    }
    
    public void setTipoIdentificacionDescripcion(String tipoIdentificacionDescripcion) {
        this.tipoIdentificacionDescripcion = tipoIdentificacionDescripcion;
    }
}


