package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoOperarioUser generated by hbm2java
 */
public class TipoOperarioUser  implements java.io.Serializable {


     private int idTipoOperarioUser;
     private String descripcion;
     private Set operarioUsers = new HashSet(0);

    public TipoOperarioUser() {
    }

	
    public TipoOperarioUser(int idTipoOperarioUser, String descripcion) {
        this.idTipoOperarioUser = idTipoOperarioUser;
        this.descripcion = descripcion;
    }
    public TipoOperarioUser(int idTipoOperarioUser, String descripcion, Set operarioUsers) {
       this.idTipoOperarioUser = idTipoOperarioUser;
       this.descripcion = descripcion;
       this.operarioUsers = operarioUsers;
    }
   
    public int getIdTipoOperarioUser() {
        return this.idTipoOperarioUser;
    }
    
    public void setIdTipoOperarioUser(int idTipoOperarioUser) {
        this.idTipoOperarioUser = idTipoOperarioUser;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getOperarioUsers() {
        return this.operarioUsers;
    }
    
    public void setOperarioUsers(Set operarioUsers) {
        this.operarioUsers = operarioUsers;
    }




}


