package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int idTipoUsuario;
     private String tipoUsuarioDescripcion;
     private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(int idTipoUsuario, String tipoUsuarioDescripcion) {
        this.idTipoUsuario = idTipoUsuario;
        this.tipoUsuarioDescripcion = tipoUsuarioDescripcion;
    }
    public TipoUsuario(int idTipoUsuario, String tipoUsuarioDescripcion, Set usuarios) {
       this.idTipoUsuario = idTipoUsuario;
       this.tipoUsuarioDescripcion = tipoUsuarioDescripcion;
       this.usuarios = usuarios;
    }
   
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getTipoUsuarioDescripcion() {
        return this.tipoUsuarioDescripcion;
    }
    
    public void setTipoUsuarioDescripcion(String tipoUsuarioDescripcion) {
        this.tipoUsuarioDescripcion = tipoUsuarioDescripcion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


