package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1

/**
 * TipoVehiculo generated by hbm2java
 */
public class TipoVehiculo  implements java.io.Serializable {


     private int idTipoVehiculo;
     private String tipoVehiculoDescripcion;

    public TipoVehiculo() {
    }

	
    public TipoVehiculo(int idTipoVehiculo, String tipoVehiculoDescripcion) {
        this.idTipoVehiculo = idTipoVehiculo;
        this.tipoVehiculoDescripcion = tipoVehiculoDescripcion;
    }
   
    public int getIdTipoVehiculo() {
        return this.idTipoVehiculo;
    }
    
    public void setIdTipoVehiculo(int idTipoVehiculo) {
        this.idTipoVehiculo = idTipoVehiculo;
    }
    public String getTipoVehiculoDescripcion() {
        return this.tipoVehiculoDescripcion;
    }
    
    public void setTipoVehiculoDescripcion(String tipoVehiculoDescripcion) {
        this.tipoVehiculoDescripcion = tipoVehiculoDescripcion;
    }

}