package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioVehiculo generated by hbm2java
 */
public class UsuarioVehiculo  implements java.io.Serializable {


     private UsuarioVehiculoId id;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private boolean activo;
     private Set ingresos = new HashSet(0);

    public UsuarioVehiculo() {
    }

	
    public UsuarioVehiculo(UsuarioVehiculoId id, Usuario usuario, Vehiculo vehiculo, boolean activo) {
        this.id = id;
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.activo = activo;
    }
    public UsuarioVehiculo(UsuarioVehiculoId id, Usuario usuario, Vehiculo vehiculo, boolean activo, Set ingresos) {
       this.id = id;
       this.usuario = usuario;
       this.vehiculo = vehiculo;
       this.activo = activo;
       this.ingresos = ingresos;
    }
   
    public UsuarioVehiculoId getId() {
        return this.id;
    }
    
    public void setId(UsuarioVehiculoId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set ingresos) {
        this.ingresos = ingresos;
    }




}


