package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 30/06/2015 12:55:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String placa;
     private TipoVehiculo tipoVehiculo;
     private String marca;
     private String color;
     private String modelo;
     private Date fechaRegistro;
     private Set usuarioVehiculos = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String placa, TipoVehiculo tipoVehiculo, String marca, String modelo, Date fechaRegistro) {
        this.placa = placa;
        this.tipoVehiculo = tipoVehiculo;
        this.marca = marca;
        this.modelo = modelo;
        this.fechaRegistro = fechaRegistro;
    }
    public Vehiculo(String placa, TipoVehiculo tipoVehiculo, String marca, String color, String modelo, Date fechaRegistro, Set usuarioVehiculos) {
       this.placa = placa;
       this.tipoVehiculo = tipoVehiculo;
       this.marca = marca;
       this.color = color;
       this.modelo = modelo;
       this.fechaRegistro = fechaRegistro;
       this.usuarioVehiculos = usuarioVehiculos;
    }
   
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public TipoVehiculo getTipoVehiculo() {
        return this.tipoVehiculo;
    }
    
    public void setTipoVehiculo(TipoVehiculo tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getUsuarioVehiculos() {
        return this.usuarioVehiculos;
    }
    
    public void setUsuarioVehiculos(Set usuarioVehiculos) {
        this.usuarioVehiculos = usuarioVehiculos;
    }




}


